template = "https://github.com/giellalt/template-lang-und"
rev_id = 303
template_sha = "b019fafa945ec21f8f1ee983a95aba800ec89260"

[replacements]
__GLOTTOLOG_ID__ = "oldn1244"
__REPO__ = "lang-non"
__UND2C__ = "non"
__UNDEFINED__ = "Old Norse"
__UND__ = "non"
