template = "https://github.com/giellalt/template-lang-und"
rev_id = 289
template_sha = "599009dae90448ef6fe32b71f7a6880293f3d546"

[replacements]
__GLOTTOLOG_ID__ = "oldn1244"
__REPO__ = "lang-non"
__UND2C__ = "non"
__UNDEFINED__ = "Old Norse"
__UND__ = "non"
