template = "https://github.com/giellalt/template-lang-und"
rev_id = 337
template_sha = "eb8f32293ac396653b3977ae5e8a599e4091c885"

[replacements]
__GLOTTOLOG_ID__ = "oldn1244"
__REPO__ = "lang-non"
__UND2C__ = "non"
__UNDEFINED__ = "Old Norse"
__UND__ = "non"
